### ISSUE TITLE
Failed test test_popd

### ISSUE THREAD

**Issue by stesi13** [KeyWeeUsr/Butch#4]
**Env**: MacOS Big Sur
**Steps to Reproduce**: `python test.py`

FAIL: test_popd (tests.test_batchfiles.BatchFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/mock.py", line 1337, in patched
    return func(*newargs, **newkeywargs)
  File "/Users/stefansimko/Desktop/petek/Butch/butch/tests/test_batchfiles.py", line 858, in test_popd
    assert_bat_output_match(script_name, stdout.mock_calls, concat=True)
  File "/Users/stefansimko/Desktop/petek/Butch/butch/tests/test_batchfiles.py", line 53, in assert_bat_output_match
    assert left == right, (left, right)
AssertionError: (call('/private/var/folders/17/0p0_3stn7wv85fczkkcxnvgh0000gn/T', file=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>), call('/tmp', file=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>))

**Comment by KeyWeeUsr** [comment]
We can make it execute only on Linux (or in a Linux-based container) by utilizing [`sys.platform`](https://docs.python.org/3/library/sys.html#sys.platform) in the test case. The name will be different on Windows anyway, so skipping MacOS will be fine too in this particular case.

**Comment by KeyWeeUsr** [comment]
Closed by #5
